return {
    General = {
        Close = "󰅙",
        Dap = "",
        Dots = "󰇘",
        Debugger = "",
        Diagnostics = "󰒡",
        Files = "",
        Git = "",
        LSP = "",
        Package = "󰏖",
        Search = "",
        Spellcheck = "󰓆",
        Tab = "󰓩",
        Toggles = "",
        Terminal = "",
        Window = "",
    },
    Dap = {
        Stopped             = "󰁕",
        Breakpoint          = "",
        BreakpointCondition = "",
        BreakpointRejected  = "",
        LogPoint            = ".",
    },
    Diagnostics = {
        Error = "",
        Warn  = "",
        Hint  = "󰌵",
        Info  = "",
    },
    LSP = {
        Active = " ",
        Loading = "",
    },
    Git = {
        Add    = "",
        Branch = "",
        Conflict = "",
        Delete = "",
        Ignored = "◌",
        Sign = "▎",
        Staged = "",
        Modified = "",
        Removed  = "",
        Unstaged = "✗",
        Untracked = "",
    },
    File = {
        New = "",
        Modified = "",
        ReadOnly = "",
    },
    -- TODO: Lazyvim kinds version (Directly add to cmp)
    -- NOTE: https://github.com/LazyVim/LazyVim/blob/bb36f71b77d8e15788a5b62c82a1c9ec7b209e49/lua/lazyvim/plugins/coding.lua#L57
    Kinds = {
        Array         = "",
        Boolean       = "󰨙",
        Class         = "",
        Codeium       = "󰘦",
        Color         = "",
        Control       = "",
        Collapsed     = "",
        Constant      = "󰏿",
        Constructor   = "",
        Copilot       = "",
        Enum          = "",
        EnumMember    = "",
        Event         = "",
        Field         = "",
        File          = "",
        Folder        = "",
        Function      = "󰊕",
        Interface     = "",
        Key           = "",
        Keyword       = "",
        Method        = "󰊕",
        Module        = "",
        Namespace     = "󰦮",
        Null          = "",
        Number        = "󰎠",
        Object        = "",
        Operator      = "",
        Package       = "",
        Property      = "",
        Reference     = "",
        Snippet       = "",
        String        = "",
        Struct        = "󰙅",
        TabNine       = "󰏚",
        Text          = "",
        TypeParameter = "",
        Unit          = "",
        Value         = "󰎠",
        Variable      = "󰀫",
    },
}
